### ISSUE TITLE
INFINITE LOAD ON GUILD ANALYSE

### ISSUE THREAD

**Issue by konoashi** [Senither/Hypixel-Skyblock-Leaderboard#11]
![image](https://user-images.githubusercontent.com/64316846/108637307-74decf00-748a-11eb-8e40-061c4a899248.png)
![image](https://user-images.githubusercontent.com/64316846/108637317-89bb6280-748a-11eb-8d4e-7ab5db65d2c2.png)
![image](https://user-images.githubusercontent.com/64316846/108637394-ac4d7b80-748a-11eb-98ee-628ee58c8d29.png)
![image](https://user-images.githubusercontent.com/64316846/108637399-ba9b9780-748a-11eb-89eb-629186f31498.png)

**Comment by Senither** [comment]
What's the name of the guild you tried to scan?

**Comment by konoashi** [comment]
Ok isn't really a bug, One player played sb before the implementation of api and never plaeyed again so I guess there is this error because player don't have sb profile

**Comment by Senither** [comment]
Okay, can you give me the name of the guild you tried to scan tho?
With that, I can do some tests on my side and make a fix for it so it doesn't happen in the future.

**Comment by konoashi** [comment]
Guild name: Lost Soul
Guild link: https://plancke.io/hypixel/guild/player/konoashi

**Comment by Senither** [comment]
Alright, cheers for the info!
I'll look into a solution so the guild scanner works even when players haven't played SkyBlock before.

**Comment by konoashi** [comment]
okay thanks
